#ifndef CONFIG_WANICODE_H
#define CONFIG_WANICODE_H

#include "config_common.h"

#define LEADER_TIMEOUT 300

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#endif
