#pragma once

#ifdef AUDIO_ENABLE
#define AUDIO_CLICKY
#define STARTUP_SONG SONG(E1M1_DOOM)
#define GOODBYE_SONG  SONG(SONIC_RING)

#define AUDIO_CLICKY_FREQ_RANDOMNESS 1.5f
#endif

#ifndef ONESHOT_TAP_TOGGLE
#define ONESHOT_TAP_TOGGLE 2
#endif

#ifndef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 3000
#endif

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
